<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.11">
  <POU Name="PRG_TEST_LOGVIEW" Id="{5804c99e-7e2e-4244-a5e9-ac8bb77d9b4b}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM INTERNAL PRG_TEST_LOGVIEW
VAR
	bEnableTests : BOOL;
	fbLogView : FB_LogView;
	fbBase : FB_Base_Test;
	bCmdReset : BOOL;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[IF bEnableTests THEN

	fbLogView();

	fbBase();

	IF bCmdReset THEN
		bCmdReset R= GVL_Utilities.fbFaultHandler.CmdReset();
	END_IF
	
END_IF
]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>